[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "grace_to_you_sermons"
version = "0.0.1"
dependencies = [
    "requests",
    "selenium",
    "bs4",
    "loguru",
    "click"
]

[project.scripts]
gtydownload = "gtysermons.scripts:download"
